const fs = require("fs");
const path = require("path");

const pluginRoot = path.resolve(process.argv[2] || "");
if (!pluginRoot || !fs.existsSync(pluginRoot)) {
  throw new Error("Usage: node scripts/build-obsidian-single-file.js <plugin-directory>");
}

const entryPath = path.join(pluginRoot, "main.source.js");
const libDir = path.join(pluginRoot, "lib");
const outputPath = path.join(pluginRoot, "desktop.js");

if (!fs.existsSync(entryPath)) {
  throw new Error(`Missing modular entry: ${entryPath}`);
}
if (!fs.existsSync(libDir)) {
  throw new Error(`Missing module directory: ${libDir}`);
}

const moduleFiles = fs.readdirSync(libDir)
  .filter(name => name.endsWith(".js"))
  .sort()
  .map(name => ({
    id: `./lib/${name.slice(0, -3)}`,
    filePath: path.join(libDir, name)
  }));

const modules = [
  { id: "./main", filePath: entryPath },
  ...moduleFiles
];

function indent(source, spaces) {
  const prefix = " ".repeat(spaces);
  return source.split(/\r?\n/).map(line => `${prefix}${line}`).join("\n");
}

const factories = modules.map(({ id, filePath }) => {
  const source = fs.readFileSync(filePath, "utf8").replace(/^\uFEFF/, "");
  return `${JSON.stringify(id)}: function(module, exports, require, __filename, __dirname) {\n${indent(source, 4)}\n  }`;
}).join(",\n  ");

const banner = `// OE Link desktop bundle.\n// Generated from main.source.js and lib/*.js by scripts/build-desktop.js.\n// Do not edit this file directly; edit the modular sources and rebuild.\n`;

const bundle = `${banner}(function(nativeRequire, nativeModule) {
  "use strict";

  const factories = {
  ${factories}
  };
  const cache = Object.create(null);

  function normalizeLocalId(request, parentId) {
    const parentParts = String(parentId || "./main").split("/");
    parentParts.pop();
    const parts = parentParts.concat(String(request).split("/"));
    const normalized = [];
    for (const part of parts) {
      if (!part || part === ".") continue;
      if (part === "..") normalized.pop();
      else normalized.push(part);
    }
    let id = "./" + normalized.join("/");
    if (id.endsWith(".js")) id = id.slice(0, -3);
    return id;
  }

  function load(request, parentId) {
    if (!String(request).startsWith(".")) return nativeRequire(request);
    const id = normalizeLocalId(request, parentId);
    if (!Object.prototype.hasOwnProperty.call(factories, id)) {
      throw new Error("Bundled module not found: " + request + " from " + parentId);
    }
    if (cache[id]) return cache[id].exports;

    const localModule = { exports: {} };
    cache[id] = localModule;
    const filename = id + ".js";
    const dirname = id.includes("/") ? id.slice(0, id.lastIndexOf("/")) : ".";
    const localRequire = childRequest => load(childRequest, id);
    factories[id](localModule, localModule.exports, localRequire, filename, dirname);
    return localModule.exports;
  }

  nativeModule.exports = load("./main", "./entry");
})(require, module);
`;

fs.writeFileSync(outputPath, bundle, "utf8");
console.log(JSON.stringify({
  outputPath,
  bytes: Buffer.byteLength(bundle),
  modules: modules.map(module => module.id)
}, null, 2));
